FROM python:3.8-slim

# Create a user group and user
RUN groupadd --gid 1000 appuser \
    && useradd --uid 1000 --gid 1000 -ms /bin/bash appuser

# Install pip and virtualenv
RUN pip3 install --no-cache-dir --upgrade \
    pip \
    virtualenv

# Install additional packages
RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    git

# Set working directory
WORKDIR /home/appuser

# Clone the example repository
RUN git clone https://github.com/streamlit/streamlit-example.git app

# Set up the virtual environment
ENV VIRTUAL_ENV=/home/appuser/venv
RUN virtualenv ${VIRTUAL_ENV}
RUN . ${VIRTUAL_ENV}/bin/activate && pip install -r app/requirements.txt

# Expose the Streamlit port
EXPOSE 8501

# Copy the run script as root and change permissions
COPY run.sh /home/appuser
RUN chmod +x /home/appuser/run.sh

# Switch to the non-root user
USER appuser

# Set the entry point to the run script
ENTRYPOINT ["./run.sh"]
