mongodbUsernameBase64: ZGVicnVpdHM=
mongodbPasswordBase64: ZGVicnVpdHM=
mongoDbPort: 27017
mongoDbDatabase: walkwayai
embeddingsCollection: embeddings
mongoDbNodeportPort: 30000
timestamp: 20240530_105031