mongodbUsernameBase64: d2Fsa3dheQ==
mongodbPasswordBase64: d2Fsa3dheQ==
mongoDbPort: 27017
mongoDbDatabase: walkwayai
embeddingsCollection: embeddings
mongoDbNodeportPort: 30000
clusterNodeId: 172.18.0.2
timestamp: 20240530_165512