apiVersion: v1
kind: Pod
metadata:
  name: python
  labels:
    app: python
spec:
  containers:
  - name: python
    image: fabiocuri/python-walkway:latest
    command: ["sh", "-c", "while true; do sleep 30; done"]
    tty: true